### ISSUE TITLE
Region capture is not working

### ISSUE THREAD

**Issue by juanpastas** [AminaG/OpenScreenshot#25]
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.71 Safari/537.36.

I am on Chrome. Above is my user agent.

Is this enough to describe?

**Comment by butaixianran** [comment]
Same problem on Chrome 45, need a fix

**Comment by natema** [comment]
Same problem also on Chrome 50, need a fix. 
I also confirm @butaixianran's output in the console.

**Comment by AminaG** [comment]
I am remoing this option. Now you can take "visible screenshot", and crop to content
