### ISSUE TITLE
Cannot capture region of the screen

### ISSUE THREAD

**Issue by krittanat** [AminaG/OpenScreenshot#4]
Hi, I love your extension and have used it since version 14.5 before it was removed from the stored. I'm so glad that it is now back in.

However, I cannot capture region of the screen. This is the feature that I use the most. When I clicked on the menu on "capture region of the screen" nothing happens. I tried shortcut ALT+R also nothing happens.

**Comment by AminaG** [comment]
I remove this option. You can take full screenshot and crop to content
