### ISSUE TITLE
Options disappear before I can click them

### ISSUE THREAD

**Issue by ScienceofSpock** [AminaG/OpenScreenshot#45]
So I downloaded this plugin to make full page screenshots for customer email templates. Problem is that when I click the icon, the list initially shows up, but then 2 of the options just disappear, one of them being the All Page Screenshot. If I'm really quick, and lucky, I can catch it before it disappears. Some more info that may help track down this issue:
If I have the resulting screenshot page open, the menu items do NOT disappear.
For example, if I have not made any screenshots, and I want to take an all page screenshot, I click the icon. The menu shows up, then All Page Screenshot disappears. If I click Visible Screenshot, let it take a screenshot and pop the result page, then go back to the other page, when I click the icon, All Page Screenshot does NOT disappear from the menu.

**Comment by AminaG** [comment]
Very strage. But I cannot reproducte the bug. I don't get your bug.
