### ISSUE TITLE
Chrome is repeatedly giving a notice about automatic removal of WP Screenshot

### ISSUE THREAD

**Issue by matesovicz** [AminaG/OpenScreenshot#46]
Hi,
Chrome is repeatedly and constantly giving me notice saying "Extension WP Screenshot has been automatically removed". 
And that is happening even after I have removed the extension.
And now I can't even install it again, since the "shop" is now consider it as installed... :-/

It is rather annoying - the pop-up window with that notice, that constantly drags my attention away...

In the list of Chrome extensions, the WP S. is not listed.

Do you have any advice or solution for me please?

Thanks a lot,
Martin

**Comment by dannguyen** [comment]
@matesovicz you appear to be talking about a completely different plugin, one which has been accused of being a piece of malware: https://heimdalsecurity.com/blog/webpage-screenshot-leaks-private-data-million-users/

This is the Github repo for "OpenScreenshot"  https://chrome.google.com/webstore/detail/open-screenshot/akgpcdalpfphjmfifkmfbpdmgdmeeaeo?hl=en

**Comment by seahawksean** [comment]
No, this is the extension that apparently has the malware.  I just got the same notice from Chrome.  I landed here by following the path formed from links in the Chrome extensions manager under Webpage Screenshot, to your website, to your Git repo.  You might want to make sure someone hasn't placed malware in your code

**Comment by Aminadav** [comment]
The extension with the malware have the UID cki... It is not related to this extension. He is using our server for sharing the images
