### ISSUE TITLE
Print to PDF in Ubuntu always layout horizontally

### ISSUE THREAD

**Issue by WesleyBlancoYuan** [AminaG/OpenScreenshot#47]
After doing the screenshot, I choose to save the picture to PDF, and with Chromium and Ubuntu 16.04, I get a prompt that only let me choose where to save the file, and not the orientation. The pdf I get, has the original vertical webpage screenshot horizontally layouted, placing the content to the left, leaving much space to the right, and more pages. Can it be fixed?

But, if I choose to print, and I am allowed to print it to PDF in chromium, and it works well.

**Comment by AminaG** [comment]
Ok. If you can print it in Chrome. I will remove the option.
